### ISSUE TITLE
Asking for help getting started in Nav using MBF

### ISSUE THREAD

**Issue by rmerriam** [naturerobots/move_base_flex#104]
Hi,
I'm not totally new to using ROS but am new to using a navigation stack. I have a simulation working through key teleop for a 6 wheel robot - the Wild Thumper chassis. Getting navigation working is frustrating me greatly because multiple pieces of planning and mapping need to be created to make it work. There is no incremental process for getting to the totality that I can see.

My searching led me here because it seems the map is not necessary which would be at least one simplification. Or perhaps with the abstraction layer a basic system could be created and then expanded to use more complex processes.

I've looked at the Ceres robot software on Git Hub but can't grasp enough to transfer the work to my robot. I know I'm asking quite a lot but can you work through the steps with me to get navigation working in simulation with Gazebo? In return, I'll document the entire process so it can be used as a tutorial for others.

**Comment by spuetz** [comment]
Hey @rmerriam ,
so your goal is to have your robot planning a path on a pre-recorded map and the using that global plan for a controller, trying to follow that global plan, right?

It is important to know what your actual goal is. Thx. Additionally, it is important to know what sensor you have and in which terrain you are going to setup your robot and also  what kind of map you want to use. Costmap_2d?

**Comment by rmerriam** [comment]
Hi,
It will be an ongoing process of learning what I can about navigation going from the basic to more complex capabilities. I want to learn the process rather than just get it all working. 

1. Obstacle avoidance with no map moving from current location to a new location in 2d.
2. Add in map determined by exploration in 2d.
3. Use map with from 2 for navigation.
4. Add in 3d capability. 

Start with a 2d laser, add depth camera, and add an IMU once it gets to step 4. Originally in simulation but eventually in a real robot. 

Once I get through 1 and/or 2 I'll probably be fine on my own.

**Comment by spuetz** [comment]
@rmerriam 
So right now you could use the `mbf_simple_nav`. But there are no plugins (planners, controllers, recoveries) available open source. So I would skip your first step. And start with 2.) and `mbf_costmap_nav`. Here you could use [gmapping](http://wiki.ros.org/gmapping) and later in 3.) use for example [amcl](http://wiki.ros.org/amcl). For full 3D there will be a lot of work to do. So 4.) might be a bunch of work, because you need to create another MBF server and plugins performing path planning and motion control in 3D.
