### ISSUE TITLE
plugin inheritance question

### ISSUE THREAD

**Issue by MarcelSoler** [naturerobots/move_base_flex#117]
Hello! I was l trying to use Mbf instead of the old move_base.
I have encountered some problems while trying to use some plugins like http://wiki.ros.org/costmap_prohibition_layer
Looking at the tutorials I found that I have to inherit also from mbf_costmap_core. But in this particular case I don't think that could inherit from:
- costmap_controller.h 
- costmap_planner.h
- costmap_recovery.h
The same happens when I try to use spatio_temporal_boxel_layer.

I am missing something? Any help would be appreciated.

**Comment by corot** [comment]
Not really, costmap layers should work exactly as on move_base. What's exactly the problem you have?

For the record, you can make your planners/controllers/recovery behaviors inherit from mbf_costmap_core, thought it's not mandatory

**Comment by MarcelSoler** [comment]
I had a format error:  
Looking at the launch msgs I saw:  `Loading from pre-hydro parameter style`.

My plugins we're not loaded, I thought the problem was some inheritance plugin problem but I was a lot easier. Anyway thank you very much for your comment it pointed me in the right direction.   

I have another question of a different topic. I have write it here, but if you prefer I'll close this issue (is already solved) and create the proper one.

## Change costmap et runtime
What I want to do is: while navigating execute a goal with a different controller (not the default one) .
I want this controller to run with a slightly different costmap (smaller resolution... ) and a different global_frame (odom instead of map), and some different plugins params.

Maybe I'm wrong but I don't think this is possible right now. There is not an "abstract costmap" allowing to  change the costmap along with the planner in runtime.
Do you think this can be achievable? Can it be an interesting feature for move base flex?
