### ISSUE TITLE
Change costmap at runtime

### ISSUE THREAD

**Issue by spuetz** [naturerobots/move_base_flex#118]
_Originally posted by @MarcelSoler in https://github.com/magazino/move_base_flex/issues/117#issuecomment-456776803_

## Change costmap et runtime
What I want to do is: while navigating execute a goal with a different controller (not the default one) .
I want this controller to run with a slightly different costmap (smaller resolution... ) and a different global_frame (odom instead of map), and some different plugins params.

Maybe I'm wrong but I don't think this is possible right now. There is not an "abstract costmap" allowing to  change the costmap along with the planner in runtime.
Do you think this can be achievable? Can it be an interesting feature for move base flex?

**Comment by spuetz** [comment]
Hi @MarcelSoler The question is, if costmap could do a change of resolution and map frame at runtime, if yes, there should be no problem. I hadn't had this issue before. So you could figure out, if that is possible. If not you could start a second instance of MBF with another costmap – with different parameters.

**Comment by MarcelSoler** [comment]
A second instance of move base flex It's what I currently have. I wanted to get rid of the second one.  Ok thanks for the fast response!
