### ISSUE TITLE
mbf doesnt subscribe to my Laserscanner

### ISSUE THREAD

**Issue by Salem-Guezguez** [naturerobots/move_base_flex#119]
I find Mbf very awesome und I just watched your ROSCON video and I did really like it. 
I am now trying to use it on my robot( on Gazebo). I send a goal via Rviz und my robot start to move until the goal is reached. But sometimes my robot makes some collision und doesnt notice that. The robot continue to move toward the wall. I looked at the graph of (rqt_graph) und i found that mbv doesnt subscribe to my topic /scan but the old move_base does. I am really confused!!! Should mfb subscribe to my /scan topic (for my controller) ?

my launch file looks like this:
![launch_file](https://user-images.githubusercontent.com/44145344/51859305-1be9ee80-2337-11e9-87c8-9b4f8e32367b.png)

![mbf](https://user-images.githubusercontent.com/44145344/51847447-fe5b5b80-231b-11e9-86ec-4fdb3f6dcd9c.png)
![mbf_node_info](https://user-images.githubusercontent.com/44145344/51847448-fe5b5b80-231b-11e9-8cf6-f3cb0aa817a9.png)
![old_move_base](https://user-images.githubusercontent.com/44145344/51847449-fe5b5b80-231b-11e9-8fe6-55464e1ef711.png)

**Comment by spuetz** [comment]
Hey, you should use mbf_costmap_nav instead of mbf_simple_nav, since you need the costmap in your case.

**Comment by corot** [comment]
Hi @Salem-Guezguez, and sorry for the late response;
So MBF will listen to whatever sensor is configured in the costmap parameters, for example [here](https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_navigation/param/costmap_common_params.yaml#L26) is the configured laser for turtlebot. Could be that you are not loading the costmap_common_params.yaml file in your launcher? Please post here the result of:

`rosparam get /move_base_flex`

**Comment by Salem-Guezguez** [comment]
Thanks It s work  :))
I have wrong configured  my observation_sources.

**Comment by corot** [comment]
Then everybody happy! :ok_man:
