### ISSUE TITLE
Questions about future works

### ISSUE THREAD

**Issue by PPokorski** [naturerobots/move_base_flex#12]
Hi !
First of all thanks for your work. I like the idea of flexibility that you're trying to implement. Since I have two questions according future work:
1. You wrote, that you want to replace costmap2D with a grip map. What kind of grid map do you mean? [This](https://github.com/ethz-asl/grid_map) one?
2. What do you think about using multiple planner inside the move_base? For example an approach with, say, A* for global planning, Lattice Planner for a local plan and a controller for path execution?

Thanks in advance for your answers!

**Comment by corot** [comment]
Hi @PPokorski ,

1. Exactly. Work is already on progress, but cannot tell when will be ready. Do you have experience with grid_map?
2. Is also planned: instead of one planner and one controller, we will allow loading several, and choose on runtime which one to use. Would be this enough for your usecase?

Thanks for your interest!

**Comment by howardcochran** [comment]
Allowing switching between various planners at runtime is something I need.  It is also something that move_base can already do via dynamic reconfigure, which we take advantage of frequently.

**Comment by corot** [comment]
Yes. The advantage on MBF will be that plugins will be pre-loaded and pre-initialized, so transitions will be immediate. Some planners (e.g. SBPL) take quite long to initialize, so with move_base is not really feasible to switch back and forth.

**Comment by spuetz** [comment]
@howardcochran Switching between planners and controllers is now implemented and ready for testing. If you are interested, see the current master branch.

**Comment by corot** [comment]
1. grid_map integration is an ongoing (though slowly) project
2. multiple planners and controllers implemented on 8b019621a748dc073439d5907b5f1d0eeb297ad5
