### ISSUE TITLE
Allow loading multiple planners and controllers, electable at runtime

### ISSUE THREAD

**Issue by corot** [naturerobots/move_base_flex#13]
Our ROS API already provides a xxx_name field for that, but it's not implemented in the server

**Comment by reinzor** [comment]
I think also a service should be exposed to query the available planners that are configured on startup. This way, the configuration of the planners can be done on startup with use of the parameter server.

**Comment by corot** [comment]
Well, the list of loaded plugins is already available as a parameter, and it can be changed at runtime through dynamic reconfiguration.

**Comment by reinzor** [comment]
How would you like to deal with planner specific configurations?

**Comment by corot** [comment]
Each planner has his own namespace on the parameter server, so you can configure each one independently both at launch time and with dyn. reconf. if the plugin offers it

**Comment by spuetz** [comment]
I'm on it!
