### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by reinzor** [naturerobots/move_base_flex#130]
Could you provide some insight in when you are planning to do a 1.0.0 release and from there ensure ABI compatibility over ROS versions?

**Comment by reinzor** [comment]
ping

**Comment by spuetz** [comment]
Hi I was just about to answer :D So we already ensure API compatibility over two minor version changes, and we'll make things deprecated if necessary and remove these after two minor version changes. Thereby, one will have enough time to adapt to the new / not deprecated API. Minor versions are counted when new features come in. This is how we version MBF.

**Comment by spuetz** [comment]
@reinzor Btw. Since we have new navigation servers based on MBF, like one for outdoor terrain working on meshes, and on in development working on grid_map. Cheers.

**Comment by reinzor** [comment]
Thanks for the update; I was more referring to https://semver.org/#how-do-i-know-when-to-release-100 , but thanks for ensuring api compatibility :)
