### ISSUE TITLE
Wait for goal to finish running on the same slot

### ISSUE THREAD

**Issue by spuetz** [naturerobots/move_base_flex#136]
This is related to #93 and #121. There shouldn't be multiple threads running for the same slot. Also it makes sense to only accept (`setAccepted`) goals, if they are going to be processed. See: http://wiki.ros.org/actionlib/DetailedDescription#High_Level_Client.2BAC8-Server_Interaction

**Comment by corot** [comment]
Aren't we doing this already?  Now we join the canceled threads: https://github.com/magazino/move_base_flex/blob/master/mbf_abstract_nav/include/mbf_abstract_nav/abstract_action.h#L88

**Comment by spuetz** [comment]
Japp solved with PR #138
