### ISSUE TITLE
Exe_path with continous replanning

### ISSUE THREAD

**Issue by MarcelSoler** [naturerobots/move_base_flex#145]
Hi! I am setting a behaviour tree with move_base_flex, I wanted to be able to do continuous replanning while calling GetPath and ExePath. I am using the blackboard to share the path between them. 

Now I am working on calling GetPath al low freq (1/2Hz) and ExePath  higher ( 20Hz). Getting a Behaviour similar to move_base action but with more control in the logic, recoveries ...

 In #70 something similar was mentioned and I am not sure if this was resolved. 

Can someone clarify this ? or suggest a way to do it! 

Thank you,

**Comment by corot** [comment]
Hi! yes, all is working fine. We do what you are describing also with a BT, while running exe_path (here FollowPath task) and get_path (here UpdatePath) in parallel:

![image](https://user-images.githubusercontent.com/322610/61633763-0fb06f80-ac90-11e9-87a2-719bc5c67173.png)

Sending a new goal to exe_path while already running will just replace the executed path, without stopping/starting the robot, as long as you use the same concurrency slot and the same controller.

**Comment by MarcelSoler** [comment]
Nice! really nice! thank you for your quick response.
FYI I'm using https://github.com/BehaviorTree/BehaviorTree.CPP and it's very powerful and easy to use.

**Comment by artemiialessandrini** [comment]
Hi, did you compare smach with BT, how is it performing? Which one looks better to you? @MarcelSoler

**Comment by juliangaal** [comment]
> Hi! I am setting a behaviour tree with move_base_flex, I wanted to be able to do continuous replanning while calling GetPath and ExePath. I am using the blackboard to share the path between them.

Out of curiosity: Is there any reason to do this manually instead of playing with `planner_frequency`?

**Comment by Rayman** [comment]
@artemiialessandrini smach is currenly not maintained very well. There are multiple PR with no reactions. I would look for a different framework.

I've experience with smach, it works, however for new projects I'm also looking at BehaviorTree.CPP. Looks very nice.
