### ISSUE TITLE
Example of mbf_costmap_core::CostmapPlanner plugging

### ISSUE THREAD

**Issue by doisyg** [naturerobots/move_base_flex#150]
Hello,
Is there an example of a global planner implementing the  mbf_costmap_core::CostmapPlanner interface. In particular the descriptive error outcomes ?
Thx!

**Comment by corot** [comment]
https://github.com/corot/navigation/blob/use_mbf_core/navfn/src/navfn_ros.cpp

**Comment by doisyg** [comment]
Thanks! It took me quite a while to compile it for *melodic* but it works
