### ISSUE TITLE
controller updates in "real"-time in simulation

### ISSUE THREAD

**Issue by MCFurry** [naturerobots/move_base_flex#167]
While running mbf in a simulation where the simulation doesn't reach (or is not set to) a 1.0 real-time factor, mbf still calls controller execution in "real"-time since it uses the boost chrono timer:
[link](https://github.com/magazino/move_base_flex/blob/e4cdbb9f9ca0191cfd1905ff5125f67685292534/mbf_abstract_nav/src/abstract_controller_execution.cpp#L375)
This way the performance of the controller largely depends on how fast we (can) run a simulation and thus yields different results, or even problems in some scenarios, since the ROS time is not synchronous with the execution time of the controller.

Is this intended behaviour? Or how would you advise to run simulations with mbf?

**Comment by spuetz** [comment]
You're right! Thank you for mentioning this error. Honestly, I didn't think about it.

**Comment by MCFurry** [comment]
So maybe switching the timing to ROS-based timing would be the solution?
Would this in your opinion be "the best" solution?

**Comment by corot** [comment]
I suppose using [ROS Timers](http://wiki.ros.org/roscpp/Overview/Timers) will do the trick.
PR welcome!!!

**Comment by corot** [comment]
fixed on master
