### ISSUE TITLE
Shouldn't the controller receive the current robot pose and speed?

### ISSUE THREAD

**Issue by corot** [naturerobots/move_base_flex#17]
As discussed on #11, that's one of the interesting innovations on [nav2_core](https://github.com/locusrobotics/robot_navigation/blob/master/nav_core2/include/nav_core2/local_planner.h) we should probably adopt.

**Comment by james-ward** [comment]
As someone who is using your new framework on their project, I'd like to give this issue a +1.
It's really annoying to have to get this information from a TF listener or other subscription.

**Comment by corot** [comment]
It's already done. Will be merged into master this week.

**Comment by corot** [comment]
On master now
