### ISSUE TITLE
Turtlebot3 mbf example

### ISSUE THREAD

**Issue by Rayman** [naturerobots/move_base_flex#176]
Hey,

I've made a package with launch files for running mbf on a turtlebot3:
https://github.com/Rayman/turtlebot3_mbf

Do you think these are good enough to include in the documentation? I think it will give some people a good starting point for moving to this package.

**Comment by corot** [comment]
It could be a good place to add the code from MBF tutorials: SMACH and BTs. Current launcher shows the most basic operation mode of MBF: relaying simple goals to move_base action. We can add other launchers, plus the required code, to exemplify more advanced operation modes.

@spuetz, thoughts?   Do we already have a repo with ready configuration to start using MBF with FSM or BTs?

**Comment by simonbogh** [comment]
@Rayman I think this is a great idea, thank you. I didn't find any other tutorials or documentation giving a minimal working example replacing move_base (maybe I missed it somewhere).

**Comment by corot** [comment]
> @Rayman I think this is a great idea, thank you. I didn't find any other tutorials or documentation giving a minimal working example replacing move_base (maybe I missed it somewhere).

Right, right;  you are absolutely right. I'll add a link to @Rayman's TB3 bringup to the wiki.

**Comment by corot** [comment]
Added to Getting Started section of the [wiki](http://wiki.ros.org/move_base_flex)
