### ISSUE TITLE
Remove dependency on base_local_planner

### ISSUE THREAD

**Issue by spuetz** [naturerobots/move_base_flex#184]
For release purposes, we should remove the dependency on the `base_local_planner` in the `mbf_costmap_nav` package.
I would suggest to simply copy the necessary code to a mbf_costmap_util folder, which can be installed as separate library.

This enable us to enhance the existing move_base plugins with our interfaces.

**Comment by corot** [comment]
:thinking:  what's the problem of having `base_local_planner` as dependency?

**Comment by spuetz** [comment]
Circular dependency if we implement the new interface to the plugins.

**Comment by corot** [comment]
Addressed on #186
