### ISSUE TITLE
action constant variable cannot be found

### ISSUE THREAD

**Issue by hoppss** [naturerobots/move_base_flex#192]
move_base_flex/mbf_abstract_nav/src/recovery_action.cpp: In member function ‘void mbf_abstract_nav::RecoveryAction::run(mbf_abstract_nav::AbstractActionBase<mbf_msgs::RecoveryAction_<std::allocator<void> >, mbf_abstract_nav::AbstractRecoveryExecution>::GoalHandle&, mbf_abstract_nav::AbstractRecoveryExecution&)’:

move_base_flex/mbf_abstract_nav/src/recovery_action.cpp:71:52: error: ‘STOPPED’ is not a member of ‘mbf_msgs::RecoveryResult {aka mbf_msgs::RecoveryResult_<std::allocator<void> >}’
         result.outcome = mbf_msgs::RecoveryResult::STOPPED;

move_base_flex/mbf_abstract_nav/src/controller_action.cpp: In member function ‘void mbf_abstract_nav::ControllerAction::run(mbf_abstract_nav::AbstractActionBase<mbf_msgs::ExePathAction_<std::allocator<void> >, mbf_abstract_nav::AbstractControllerExecution>::GoalHandle&, mbf_abstract_nav::AbstractControllerExecution&)’:

move_base_flex/mbf_abstract_nav/src/controller_action.cpp:189:51: error: ‘STOPPED’ is not a member of ‘mbf_msgs::ExePathResult {aka mbf_msgs::ExePathResult_<std::allocator<void> >}’
         result.outcome = mbf_msgs::ExePathResult::STOPPED;
_____
these constance variable defined in .action cannot be found, move_base_flex can compile successfully in my pc ,but failed in my tx2

**Comment by spuetz** [comment]
What compiler are you using at your tx2?

**Comment by hoppss** [comment]
yes

**Comment by hoppss** [comment]
I solve this problem,  mbf_msgs was installed by apt before, it is different with current definition. so we need to reinstall mbf_msgs
