### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by croesmann** [naturerobots/move_base_flex#193]
Hey guys!

Is move_base_flex ready to be released into noetic?
It's currently, the only blocking package for the teb_local_planner.

Cheers, Chris

**Comment by spuetz** [comment]
Hey Chris, nice to hear from you. I can to that in the next days or on the weekend. Cheers ;)

**Comment by doisyg** [comment]
That would be nice to release it now noetic is out. Mbf compiles without issue

**Comment by spuetz** [comment]
Hi, I'm on it! Sorry, for the delay.

**Comment by croesmann** [comment]
no problem ;-)
I just saw that the travis build for noetic is failing. I guess you need to switch from the legacy branch in [industrial-ci](https://github.com/ros-industrial/industrial_ci) to the master branch in your .travis.yml by checking it out explicitly (see [here](https://discourse.ros.org/t/industrial-ci-rollout-of-version-0-10-0-with-ros2-github-actions-support/13582)

**Comment by spuetz** [comment]
See #216
