### ISSUE TITLE
ConcurrencySlots for Controllers

### ISSUE THREAD

**Issue by dorezyuk** [naturerobots/move_base_flex#241]
Hey guys,

As far as i understand, we can run multiple controller executions in parallel. This seems really dangerous and I dont know if there is a real use case for that. Is this relevant for any application?

**Comment by spuetz** [comment]
Why should this be dangerous? There are applications with multiple robots ;)

**Comment by dorezyuk** [comment]
Ah I see. And you would like to control multiple machines from one mbf server? I was thinking that on one machine this would result in something weird. Like having two controllers executing contradicting plans

**Comment by spuetz** [comment]
This was the idea, there is still some work to do for this, but currently it is not bad having this half ready option in. cheers.
