### ISSUE TITLE
Release date of mesh navigtion feature

### ISSUE THREAD

**Issue by roboticsai** [naturerobots/move_base_flex#245]
What is the plan of this repo to release the mesh navigation feature in this stack for 3d navigation? 
I saw that even the mesh [navigation](https://github.com/RudraRobotics/mesh_navigation/tree/master/mbf_mesh_nav) repo hasn't implemented this feature which the users can use on their application. 
When can the users expect this features to be complet?

**Comment by spuetz** [comment]
>  I saw that even the mesh navigation repo hasn't implemented this feature which the users can use on their application.

What do you mean?`As this is open source users should not expect anything ;) But, the release of the mesh navigation stack will happen in the next weeks. Anyway, your issue would make much more sense in the mesh navigation repo.
