### ISSUE TITLE
Actionlib bug when planner_frequency is anything other than 0

### ISSUE THREAD

**Issue by r0gi** [naturerobots/move_base_flex#259]
**ROS:** Noetic
**Package:** ros-noetic-move-base-flex 0.3.4-1focal.20210112.101859

**planners.yaml:**
```
planners:
  - name: 'planner'
    type: 'global_planner/GlobalPlanner'
```

I get the following console output when setting the global planner_frequency to anything other than 0hz:

```
BUG: Got a transition to CommState [ACTIVE] when in SimpleGoalState [DONE]
BUG: Got a second transition to DONE
```

The global planner only ends up publishing a total of 2 times /to `move_base_flex/planner/plan` and on the second time it outputs the above messages to the console.

This bug only happens only once per navigation goal. The robot does end up reaching its target however, and I get the `GOAL Reached!` message successfully.

**Comment by corot** [comment]
@r0gi, can u retry with current master?  I think this issue should be fixed now
