### ISSUE TITLE
Transitioning goal lost cause move_base_flex die

### ISSUE THREAD

**Issue by echo4echo** [naturerobots/move_base_flex#260]
I used the move_base_flex in my project and found a issue in my test. When the robot was sitting the "Black zone" in the global map (That would happen when robot localization is not excatly correct or manually mis-operating), after exceeding the patience time, the move_base_flex would die.
![Screenshot from 2021-02-18 16-20-54](https://user-images.githubusercontent.com/39905476/108447424-ccb6e380-729a-11eb-80c5-4797c1a51da1.png)

**Comment by dorezyuk** [comment]
Thanks for submitting. Could you upload the coredump from the node?

**Comment by corot** [comment]
@echo4echo, can u retry with current master?  I think this issue should be fixed now

**Comment by echo4echo** [comment]
@corot 
Hey, Corot, sorry for the late reply. Currently our robot is under maintenance. I will pull down and rerun again when I get the time slot to use the robot.

**Comment by corot** [comment]
Hopefully solved with #267; @echo4echo, please reopen if you still find the issue with current master
