### ISSUE TITLE
Allow to choose if the CheckPose/CheckPath services start with the padded footprint

### ISSUE THREAD

**Issue by dorezyuk** [naturerobots/move_base_flex#275]
### Problem
Currently the CheckPose/CheckPath services start of with the unpadded footprint. While providing the safety_dist field to the user, such that he/she can request additional padding, this API is a little bit incomplete/cumbersome for the use case where I want to use the exact same padding as used for the planning/controlling operation: This would mean, that the user would need to access the namespace of the desired costmap and search for the padding. 

### Proposal 
Instead I would propose to add an additional flag to the service definitions 
```
bool use_padded_footprint
```
Which should default to false (and thus resulting in the same behavior as now). Setting it to true would lead us to use the padded footprint from the requested costmap.

What do you think?

**Comment by corot** [comment]
Yup, sounds very reasonable. Do I PR for noetic or master or both?
But this is from june,,, do you still want it,  @dorezyuk ?
