### ISSUE TITLE
move_base_legacy_relay.py cancel navigation implementation

### ISSUE THREAD

**Issue by fllay** [naturerobots/move_base_flex#277]
It seems that move_base_legacy_relay.py  does not relay  /move_base/cancel to /move_base_flex/move_base/cancel. Or did I miss something here?

**Comment by Rayman** [comment]
You are probably right. As far as I can see, the relay doesn't handle preemption. That would be a good candidate for a PR.

**Comment by ju-mingyue** [comment]
@Rayman  When I use the move_base_flex function package again, I follow the link [https://github.com/uos/ceres_robot/blob/master/ceres_navigation/launch/move_base_flex.launch](url) to configure the file, but after running it, it is found in the node graph that this function package does not subscribe to the map and the lidar signal (the topic here is corresponding), and I can’t read it To the planned path.I don’t quite understand what does move_base_legacy_relay do?

**Comment by Rayman** [comment]
The interface of `move_base_flex` is `get_path` and `exe_path`. This is different from the old `move_base`. So there is a node `move_base_legacy_relay` that makes `move_base_flex` also provide the old interface for backwards compatibility.

With this you have a drop-in replacement for `move_base`. But when you start using `move_base_flex` fully, you won't need it anymore.

**Comment by ju-mingyue** [comment]
@Rayman 
Thank you very much for your prompt reply. Now my function package causes the robot to not run continuously. After the target point is reached, the robot will not run if the command is issued again.When using move_base, it is fully capable of multi-point navigation, but after replacing move_base_flex, it can only be a single point, and it is not clear how to publish the path planned by oneself to the robot.
![深度截图_选择区域_20211122182854](https://user-images.githubusercontent.com/81499872/142846249-dfb1227a-1d3a-49ab-95f8-3fdde2b038a4.png)
Below is the running file of my node graph and configuration：
![深度截图_选择区域_20211122183023](https://user-images.githubusercontent.com/81499872/142846393-678e3bd9-c73e-4dce-b648-e9f4b911616e.png)
![深度截图_选择区域_20211122182937](https://user-images.githubusercontent.com/81499872/142846409-aa21f5cf-fd51-4471-8e2e-c7c0a4149b70.png)

Look forward to your reply。

**Comment by Rayman** [comment]
The Github issue tracker is meant for reporting bugs and discussing features. It is not a question/answer site. You are hijacking a feature request thread about a cancel implementation.

I think you can better ask your question on https://answers.ros.org/questions/
