### ISSUE TITLE
MBF ROS Testing v 0.4.0 Costmap library load exception

### ISSUE THREAD

**Issue by FabianSchurig** [naturerobots/move_base_flex#280]
With the latest ROS Testing release version 0.4.0 we face the following error:

![image - 2021-10-27T224429 244](https://user-images.githubusercontent.com/82603417/139144201-0480777d-ca4a-4378-a649-4118a65656af.png)
```
terminate called after throwing an instance of 'pluginlib::CreateClassException'
 what(): MultiLibraryClassLoader: Could not create object of class type costmap_2d::StaticLayer as no factory exists for it 
```

The error is thrown after there is a `map -> base_link` transform from our SLAM as well as a `/map`. So after mbf tries to create the costmap layer plugin.

```
global_costmap:
  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
```

```
<launch>
  <node pkg="mbf_costmap_nav" type="mbf_costmap_nav" respawn="true" name="move_base_flex">
    <rosparam file="$(find <config_package>)/costmap_config/global.yaml" command="load"/>
  </node>
</launch>
```

Do you face a similar behavior?

**Comment by spuetz** [comment]
Sorry, but I cannot reproduce the error. Which ROS distro are you using?

**Comment by FabianSchurig** [comment]
Thanks for checking. Using noetic. It works now.

Seemed to be an API break with our costmap_2d version. Redeployed mbf, works now.
