### ISSUE TITLE
The move_base_flex function package cannot go to a new target point after reaching the target point?

### ISSUE THREAD

**Issue by ju-mingyue** [naturerobots/move_base_flex#284]
Hello, when I use the move_base_flex function package, it appears that the robot cannot reach a new target point after reaching the first target point. At the same time, I added the dwa' planner to the controllers file. The running result is as follows:
`controllers:
  - name: dwa
    type: dwa_local_planner/DWAPlannerROS
  - name: PathTrackingPID
    type: path_tracking_pid/TrackingPidLocalPlanner
PathTrackingPID:
  holonomic_robot: false
  track_base_link: true
  estimate_pose_angle: false
  base_link_frame: base_link
  Kd_ang: 0.3
  Kd_lat: 0.3
  Ki_ang: 0.0
  Ki_lat: 0.0
  Kp_ang: 1.0
  Kp_lat: 1.0
  l: 2.0
  feedback_ang: false
  feedback_lat: true
  feedforward_ang: false
  feedforward_lat: true
  controller_debug_enabled: true
  target_end_x_vel: 0.0
  target_x_acc: 2.0
  target_x_decc: 2.0
  target_x_vel: 2.0
  abs_minimum_x_vel: 0.025
  max_error_x_vel: 1.0
  max_yaw_vel: 2.0
  max_yaw_acc: 2.0
  min_turning_radius: 0.0

  use_mpc: false
  mpc_max_error_lat: 0.5
  mpc_max_fwd_iter: 200
  mpc_max_vel_optimization_iterations: 5
  mpc_min_x_vel: 0.5
  mpc_simulation_sample_time: 0.05

  anti_collision: true
  obstacle_speed_reduction: true
  collision_look_ahead_resolution: 1.0  # [m]

dwa:
  max_vel_x: 0.8 #0.5
  min_vel_x: 0.0  
  max_vel_y: 0.0
  min_vel_y: 0.0  
  max_vel_trans: 0.8 
  min_vel_trans: 0.1  
  trans_stopped_vel: 0.02 
  max_vel_theta:  0.9 #0.9 #
  min_vel_theta: 0.2 #0.3  
  theta_stopped_vel : 0.1 
  acc_lim_x:  1 #2.0 #1.5 #0.8 
  acc_lim_theta: 1 #9 #10  
  acc_lim_y: 0.0 
 
  meter_scoring: true         
  yaw_goal_tolerance: 0.1 
  xy_goal_tolerance: 0.15 
  latch_xy_goal_tolerance: false 

  sim_time: 1.2 #1.5      
  sim_granularity: 0.025
  vx_samples: 10 #20       
  vy_samples: 0.0       
  vth_samples: 20 #40 

  path_distance_bias: 0.1 #64  #30 #64    
  goal_distance_bias: 40 #20   #20 #24  #0.6 #1.2 #20 
  occdist_scale: 0.01 #0.05 #0.1 #0.2 #0.5            
  forward_point_distance: 0.325 
  stop_time_buffer: 0.2        
  scaling_speed: 0.25           
  max_scaling_factor: 0.2      

  oscillation_reset_dist: 0.05  # 0.05   
  publish_traj_pc : true 
  publish_cost_grid_pc: true  

  holonomic_robot: false

  global_frame_id: odom
  map_frame: map

  controller_frequency: 10.0
  controller_max_retries: 0
`
![深度截图_选择区域_20211123140657](https://user-images.githubusercontent.com/81499872/142978577-42352194-434d-46c3-ac13-b73f652c50eb.png)

Is this because our feature pack does not support it? Or do you need other configuration methods?

**Comment by dorezyuk** [comment]
Sorry but your question seems little to do with the move_base_flex package: move_base_flex just calls the controller you specify and if the controller fails, it cannot do much about it
