### ISSUE TITLE
Move_base_flex can’t realize the recovery function after adding the recovery function package?

### ISSUE THREAD

**Issue by ju-mingyue** [naturerobots/move_base_flex#285]
Hello, when I use the move_base_flex function package, The following problem occurred:
![深度截图_gnome-terminal-server_20211202173821](https://user-images.githubusercontent.com/81499872/144396981-76cd4b8e-4ebe-4fa1-8a24-1f587e3c604e.png)
![深度截图_gnome-terminal-server_20211202173811](https://user-images.githubusercontent.com/81499872/144396998-e268adfe-7912-4e03-a09f-c75e15755d19.png)

**Comment by spuetz** [comment]
This is a problem with your SMACH! The Issues here are only for bugs or suggestions for improvement within MBF. This is not a question/answer page! Ask your question on https://answers.ros.org/questions/
