### ISSUE TITLE
move_base action: cancel previous goal if get_path fails upon receiving a new one

### ISSUE THREAD

**Issue by corot** [naturerobots/move_base_flex#290]
Current behavior:

1. send a valid goal with RViz
2. while the robot goes there, send another goal to an invalid place, e.g. a wall
3. get_path will fail, executing the recovery behaviors
4. but robot will keep going to the original goal

https://user-images.githubusercontent.com/322610/150661159-d0a427c8-3150-4def-8bbd-f9f3e5fa2828.mp4

Not a big issue, but current is not the expected behavior:

1. send a valid goal with RViz
2. while the robot goes there, send another goal to an invalid place, e.g. a wall
3. get_path will fail, executing the recovery behaviors
4. robot stops and fail with a GetPathResult error

https://user-images.githubusercontent.com/322610/150661158-5aa3569f-f0a6-4646-9e81-27ee6eee8708.mp4

**Comment by corot** [comment]
I have pushed the fix on master by mistake :see_no_evil:, sorry
https://github.com/magazino/move_base_flex/commit/a5c19cb8f3135679e4f8f36a9ec6123b121d69ab
I don't think it's worth doing a push force to revert it, so @dorezyuk , @spuetz , can u make a postmortem review, just in case I need to revert it?  Thanks!

**Comment by spuetz** [comment]
> I have pushed the fix on master by mistake see_no_evil, sorry [a5c19cb](https://github.com/magazino/move_base_flex/commit/a5c19cb8f3135679e4f8f36a9ec6123b121d69ab) I don't think it's worth doing a push force to revert it, so @dorezyuk , @spuetz , can u make a postmortem review, just in case I need to revert it? Thanks!

looks good to me. -- Sebastian

**Comment by dorezyuk** [comment]
also good for me

**Comment by corot** [comment]
:relieved:

**Comment by corot** [comment]
Fixed with a5c19cb
