### ISSUE TITLE
Failed to load wave front planner and mmp planner

### ISSUE THREAD

**Issue by JACKLiuDay** [naturerobots/move_base_flex#328]
Hi, thank you for your great job about mbf. My PC is ubuntu 20.04 with noetic. I install mbf by sudo apt install ros-noetic-move-base-flex and mesh-navigation, pluto robot... But when I launch the pluto robot simulation, something wrong happened. 
 roslaunch pluto_gazebo pluto_botanical_garden.launch
roslaunch pluto_navigation botanical_garden_osnabrueck.launch
![image](https://github.com/magazino/move_base_flex/assets/30967867/fb1a47c1-a858-4929-a607-051daef0f4f8)

**Comment by 12ahmed52** [comment]
hello did you solve this issue ? i have the same issue

**Comment by Rayman** [comment]
According to your error message, the planner is not found. This means either:
- The planner is not installed or compiled
- The planner doesn't export the plugin correctly

Maybe you could file your bug into the bugtracker of the planner?
