### ISSUE TITLE
Compute current velocity for the controller.

### ISSUE THREAD

**Issue by spuetz** [naturerobots/move_base_flex#34]

**Comment by reinzor** [comment]
Would adding an odom helper suffice?

https://github.com/ros-planning/navigation/blob/melodic-devel/base_local_planner/include/base_local_planner/odometry_helper_ros.h

**Comment by spuetz** [comment]
That would do the job, yes! Thank you for the suggestion.

**Comment by corot** [comment]
Addressed on issue #187 and PR #189
