### ISSUE TITLE
Clean up and sort parameter namespaces

### ISSUE THREAD

**Issue by spuetz** [naturerobots/move_base_flex#40]
This should not be:

> /move_base_flex/TrajectoryPlannerROS/holonomic_robot
> /move_base_flex/controller/holonomic_robot
> /move_base_flex/holonomic_robot

**Comment by corot** [comment]
:+1: 

For common controller parameters, the first line should not exist at all, as all well behaved plugins use ~/<name> as namespace, with:

`ros::NodeHandle private_nh("~/" + name);`

As name is 'controller' or 'planner' or 'my_super_controller', that is, the name given to the controller or planner, not the plugin name, the second line is the used one.

But in the particular case of 'holonomic_robot', a really fundamental parameter that makes sense at MBF namespace level, the controller plugin should probably read at '~' namespace, not "~/" + name.
