### ISSUE TITLE
[wiki][Tutorials] SMACH

### ISSUE THREAD

**Issue by naveedhd** [naturerobots/move_base_flex#5]
Not sure where to put it so placing it here. In the [tutorial](http://wiki.ros.org/move_base_flex/Tutorials/Simple%20SMACH%20for%20Move%20Base%20Flex), the transitions for `WAIT_FOR_GOAL` are defined as: 

```
transitions={
    'invalid': 'GET_PATH',
    'valid': 'WAIT_FOR_GOAL',
    'preempted': 'preempted'
}
```

Shouldn't it be like `valid -> GET_PATH` and `invalid -> WAIT_FOR_GOAL` or am I missing something?

**Comment by spuetz** [comment]
We will add tutorials, as soon as mbf is released an stable.

**Comment by naveedhd** [comment]
Great, Thanks!
