### ISSUE TITLE
[move_base_legacy_relay.py] action result: status, error_msg

### ISSUE THREAD

**Issue by naveedhd** [naturerobots/move_base_flex#6]
logdebug message in [move_base_legacy_relay#L41](https://github.com/magazino/move_base_flex/blob/master/move_base_flex/scripts/move_base_legacy_relay.py#L41) is incorrect: [move_base_flex_msgs/action/MoveBase.action](https://github.com/magazino/move_base_flex/blob/master/move_base_flex_msgs/action/MoveBase.action) does not have fields `result` and `error_msg`. 

This will end up with following stacktrace:
```
[ERROR] [1504259614.237105, 752.653000]: Exception in your execute callback: 'MoveBaseResult' object has no attribute 'status'
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/me/ws/src/move_base_flex/move_base_flex/scripts/move_base_legacy_relay.py", line 43, in mb_execute_cb
    rospy.logdebug("MBF execution completed with status [%d]: %s", result.status, result.error_msg)
AttributeError: 'MoveBaseResult' object has no attribute 'status'
```

**Comment by corot** [comment]
Solved. Thanks!
