### ISSUE TITLE
How to use move_base_flex in robot navigation?

### ISSUE THREAD

**Issue by baidu31** [naturerobots/move_base_flex#60]
I want to use move_base_flex in robot navigation instead of move_base, but I cannot configure luanch file to load global_planner and local_planner. So, I will appreciate if someone can help me, thank you very much!

**Comment by corot** [comment]
Hi @baidu31, I'm cleaning up old issues. I will close this one as properly answered by @spuetz. Feel free to reopen or comment back if you need further details
