### ISSUE TITLE
Does move_base_flex offer better performance than move_base?

### ISSUE THREAD

**Issue by shrijitsingh99** [naturerobots/move_base_flex#62]
Does it support multi threading or CUDA acceleration?

**Comment by corot** [comment]
Not at all. That's not the goal. The goal is to allow users to execute smarter navigation strategies by using the extended interface.

Using it the old good way, with a monolithic move_base action, you won't get any better navigation (though you will actually get much more detailed feedback and result)

**Comment by corot** [comment]
Question answered, so...
