### ISSUE TITLE
 Stop the robot during aborting from the `exe_path` action

### ISSUE THREAD

**Issue by alireza-hosseini** [naturerobots/move_base_flex#64]
As it's clear in this line: https://github.com/magazino/move_base_flex/blob/9c5fb1b47b94a32d575b5544466fb4d15450c8f7/mbf_abstract_nav/src/abstract_controller_execution.cpp#L462 the robot wouldn't stop after aborting from the `exe_path` action, which is very problematic when there is no watchdog to stop the robot if it doesn't receive any new cmd_vel. 
Also with the current implementation, the name of the `stopMoving` doesn't make sense, because it doesn't really do what it can be inferred from its name. I also understand the point of commenting out this line and it can be useful, but I would separate the implementation of these two cases.

**Comment by corot** [comment]
I agree...  makes fully sense to send a zero velocity when interrupting the controller. But then we need a nice way to start following a new plan without stopping the controller. Maybe we can add another service: new_path that just pass the new path to the controller w/o stopping it, or does nothing if controller is not working.

For the stopMoving method... well, it actually stops motion by interrupting the controller thread. What do you mean exactly, @alireza-hosseini? What would you propose instead?

**Comment by alireza-hosseini** [comment]
@spuetz Thanks for your fast reply,
@corot About the `stopMoving` method, what I meant was since it's just interrupting the thread, the code inside the `catch` statement of the thread will be executed which stops the controller from planning not the robot itself, so it's a bit confusing. I think the solution can be simpler if we just publish the zero command velocity in case of preemption or even we can let the action client decide about that by adding a new boolean field for example to the `ExePath` action goal and only if the value is `True` it will publish the zero.

**Comment by spuetz** [comment]
@corot Should we comment-in that line for now, and rethink the replanning strategy here?

**Comment by corot** [comment]
for me , ok.

@alireza-hosseini, I agree is bad naming, but is coherent, because "moving" here really means "controlling", not physical robot motion
