### ISSUE TITLE
Question about computeVelocityCmd inheritance in mbf_costmap_nav

### ISSUE THREAD

**Issue by SHTseng** [naturerobots/move_base_flex#66]
Function computeVelocityCmd in costmap_controller_execution intends to override the one in base class. 
[computeVelocityCmd in abstract](https://github.com/magazino/move_base_flex/blob/master/mbf_abstract_nav/include/mbf_abstract_nav/abstract_controller_execution.h#L207),     [computeVelocityCmd in costmap_nav](https://github.com/magazino/move_base_flex/blob/master/mbf_costmap_nav/include/mbf_costmap_nav/costmap_controller_execution.h#L85) 

To my understanding, the override function needs to take same inputs as base class function in c++. I've test it with output message which shows the move_base_server is calling the abstract one. Also, I'm using the latest commit in master branch.

Just want to clarify if this is an intentional move, please correct me if there is any misunderstanding, thanks!

**Comment by corot** [comment]
You are right. Thanks for detecting it! I PRequested a patch

**Comment by corot** [comment]
Hi @SHTseng. I merged a fix. Would you mind to give it a second try to master branch?
Thanks!

**Comment by SHTseng** [comment]
Hi, I've tested it with turtlebot, now it is calling the overriding function and works well. 
Thanks for the fix!

**Comment by corot** [comment]
Thanks!
