### ISSUE TITLE
Predefining paths for robot to follow

### ISSUE THREAD

**Issue by aarontan-git** [naturerobots/move_base_flex#73]
hello,

According to the answer on [this](https://answers.ros.org/question/294278/custom-global-path/?answer=294286#post-id-294286) 

Can anyone provide me with some help to send the move_base_flex action server an exepath.action with predefined array of poses so that I can use local planners to follow this path?

Thanks,
Aaron

**Comment by corot** [comment]
This is a help request more than an issue, so I'll close and answer on ROS answers
