### ISSUE TITLE
Crash when not loading any controllers

### ISSUE THREAD

**Issue by LoyVanBeek** [naturerobots/move_base_flex#81]
Issue occurs when using a binary: `ros-kinetic-move-base-flex`, Version: `0.1.0-1xenial-20180824-182727-0800`

This issue has been resolved in newer versions of MBF (4f00582d3980b5a630f2ec5c068753b9c491fe11) which are currently not yet released as binaries, so I'm posting this as a heads up for potential other and as a thank-you for already fixing this!

MBF crashed because I tried to make a minimal example of using a nav_core::BaseGlobalPlanner plugin. For various reasons, my local planner runs a separate node so I did not configure any controllers. 
In that configuration, MBF crashed after my plugin's makePlan was called. When makePlan did nothing and just returns true, no crash occurred.

In the newer version, if there is no (controller) plugin loaded, you end up with a message ["No plugins loaded at all"](https://github.com/magazino/move_base_flex/blob/4f00582d3980b5a630f2ec5c068753b9c491fe11/mbf_abstract_nav/src/abstract_navigation_server.cpp#L201)

Compiling the latest version from source fixed my issue.

**Comment by corot** [comment]
Thanks for the feedback. We are about to release 0.2.0, featuring concurrent execution of actions.
