### ISSUE TITLE
Segfault during plugin initiailization

### ISSUE THREAD

**Issue by hjanott** [naturerobots/move_base_flex#82]
MBF segfaults in the plugin manager when for instance MBF fails to load a controller plugin and the function initializeControllerPlugin returns false.

**Comment by corot** [comment]
Hi @hjanott, can you explain how to reproduce? Making initializeControllerPlugin return false doesn't crash. But maybe this got fixed with the recent changes. Could you retry with latest master? And if still crashes, send a stacktrace and a recipe on how to reproduce?
Thanks!

**Comment by spuetz** [comment]
So yes @hjanott and I, we recognized that bug together. I'll test that again.

**Comment by spuetz** [comment]
Close issue, since I cannot reproduce the bug.
