### ISSUE TITLE
get_path and exe_path actions leak a thread every invocation

### ISSUE THREAD

**Issue by howardcochran** [naturerobots/move_base_flex#87]
I wrote a test loop that invokes the get_path action repeatedly, watching for leaks.  I found that each call resulted in the leak of one thread.  After thousands of calls, the server crashes because the attempt to mmap() a new thread stack fails.  This was reproduced on release 0.2.0 running in kinetic.

**Comment by howardcochran** [comment]
@corot, thank you for your alternate and better fix for the thread stack leak. I will test it shortly in my environment.

**Comment by corot** [comment]
This should be fixed on last release, 0.2.1. Thanks for reporting!
