### ISSUE TITLE
0.2.0 failing to build on Debian Stretch

### ISSUE THREAD

**Issue by mikaelarguedas** [naturerobots/move_base_flex#90]
`mbf_abstract_nav` [fails to compile on Debian Stretch](http://build.ros.org/job/Lbin_ds_dS64__mbf_abstract_nav__debian_stretch_amd64__binary/20/) for versions `0.2.0-0` and `0.2.0-1`, more details can be found on the Pull Requests releasing these packages in ROS Lunar: https://github.com/ros/rosdistro/pull/19106 and https://github.com/ros/rosdistro/pull/19182

**Comment by corot** [comment]
Should be fixed on 0.2.1. Sorry for the inconvenience .
